ID_no=input("Input your ID number: ")
firstname=input("Input your first name: ")
lastname=input("Input your last name: ")
midname=input("Input your middle name: ")
age=input("Input your age: ")
course=input("Input your course: ")
section=input("Input your section: ")
year=input("Input your grade level. (ex: 3rd year): ")
birthday=input("Input your birthday: ")
house_number=input("Input your house number: ")
street=input("input the street of your address: ")
barangay=input("Input your barangay: ")
city=input("Input your city: ")
province=input("Input your province: ")

statement=f"""I am {lastname}, {firstname} {midname}. I am a BASC {year} college student
I am {age} years old, studying at the {course} course of section {section}. My ID number is {ID_no}
My birthday was {birthday}. I live at {house_number}, {street}, {barangay}, {city}, {province}"""
print("_______________________________________________________________________________________")
print(statement)
print("_______________________________________________________________________________________")
print("Paragraph length is:", len(statement))
print("_______________________________________________________________________________________")
print("Here are the data types:")
print("ID number type is:", type(ID_no))
print("First name type is:", type(firstname))
print("Last name type is:", type(lastname))
print("Middle name type is:", type(midname))
print("Age type is:", type(age))
print("Course type is:", type(course))
print("Section type is:", type(section))
print("Year type is:", type(year))
print("Birthday type is:", type(birthday))
print("House number type is:", type(house_number))
print("Street type is:", type(street))
print("Barangay type is:", type(barangay))
print("City type is:", type(city))
print("Province type is:", type(province))

